export const projects = [
  {
    title: 'DisneyPlus',
    description: "create Disney+ CLONE using React, Firebase, Redux, and Styled Components.",
      image: '/images/plus_1.jpg',
      tags: ['Firebase', 'Redux', 'React', 'Styled Component'],
    source: 'https://github.com/MoamenZakariaMohamed/Disney-Plus',
    visit: 'https://disney-edff2.web.app',
    id: 0,
  },
  {
    title: 'E-Digital currencies',
    description: 'Digital currencies with React js i used ant desing , redux toolkit ,axios,moment ,millify and Chart.js',
    image: '/images/cur.png',
    tags: ['React', 'Redux toolkit' ,'chartjs'],
    source: 'https://github.com/MoamenZakariaMohamed/Digital',
    visit: 'https://digitalcurren.netlify.app/',
    id: 1,
  },
  {
    title: 'Basic Search engine',
    description: "This is a basic google search using reactjs ,tailwind CSS, Rapid API and context api and react loader.",
      image: '/images/basi.png',
      tags: ['React', 'tailwind CSS', 'Rapid API'],
    source: 'https://github.com/MoamenZakariaMohamed/gogle-sear',
    visit: 'https://basic-search-engin.netlify.app',
    id: 2,
  },
  {
    title: 'Airbnb',
    description: "This is a code repository for the Airbnb ",
    image: '/images/air.png',
    tags: ['React'],
    source: 'https://github.com/MoamenZakariaMohamed/airbnb-exa/tree/master',
    visit: 'https://airbanb.netlify.app/',
    id: 3,
  },
  {
    title: 'Tesla',
    description: "This is a code repository for the Tesla Clone ",
    image: '/images/tesla.png',
    tags: ['React.JS', 'Styled Components' ,'Redux'],
    source: 'https://github.com/MoamenZakariaMohamed/TESLA/tree/main',
    visit: 'https://myteslaex.netlify.app/',
    id: 4,
  },
  {
    title: 'E-commerce App',
    description: "This is a code repository for the Ecommerce app ",
    image: '/images/her.jpg',
    tags: ['React'],
    source: 'https://github.com/MoamenZakariaMohamed/E-Commerce/tree/main',
    visit: 'https://shobystore.netlify.app/',
    id:5,
  },
];